### ISSUE TITLE
"npm run test" Tests Running Is Failing With Error

### ISSUE THREAD

**Issue by mdfazuluddin** [pamtbaau/electron-angular-sqlite-bootstrap-webpack#9]
Hi,

I am getting following error when I run "npm run test", is it anything I missed? please provide the solution.

ReferenceError: require is not defined
    at Object.fs (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:104775:1)
    at __webpack_require__ (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:20:30)
    at Object../src/app/model/thedb.ts (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:104418:12)
    at __webpack_require__ (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:20:30)
    at Object../src/app/model/hero.ts (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:104218:17)
    at __webpack_require__ (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:20:30)
    at Object../src/app/model/hero.spec.ts (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:104119:16)
    at __webpack_require__ (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:20:30)
    at webpackContext (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:104090:9)
    at Array.forEach (<anonymous>)
    at Module../config/karma-test-shim.js (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:133:19)
    at __webpack_require__ (http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:20:30)
    at http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:84:18
    at http://localhost:9876/base/karma-test-shim.js?d3a955a567f2e6921e990e46decc2d0e1a4dc49b:87:10
Electron 6.1.7 (Node 12.4.0) ERROR
  An error was thrown in afterAll
  ReferenceError: require is not defined
      at Object.fs (webpack:///external%20%22fs%22:1:1 <- karma-test-shim.js:104775:1)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:1 <- karma-test-shim.js:20:30)
      at Object../src/app/model/thedb.ts (webpack:///src/app/model/thedb.ts:1:1 <- karma-test-shim.js:104418:12)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:1 <- karma-test-shim.js:20:30)
      at Object../src/app/model/hero.ts (webpack:///src/app/model/hero.ts:1:1 <- karma-test-shim.js:104218:17)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:1 <- karma-test-shim.js:20:30)
      at Object../src/app/model/hero.spec.ts (webpack:///src/app/model/hero.spec.ts:1:1 <- karma-test-shim.js:104119:16)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:1 <- karma-test-shim.js:20:30)
      at webpackContext (webpack:///src%20sync%20/.spec/.ts:8:1 <- karma-test-shim.js:104090:9)
      at Array.forEach (<anonymous>)
      at Module../config/karma-test-shim.js (webpack:///config/karma-test-shim.js:16:1 <- karma-test-shim.js:133:19)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:1 <- karma-test-shim.js:20:30)
      at webpack:///webpack/bootstrap:83:1 <- karma-test-shim.js:84:18
      at karma-test-shim.js:87:10

Electron 6.1.7 (Node 12.4.0): Executed 0 of 0 ERROR (0.266 secs / 0 secs)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular7-electron4-sqlite3-bootstrap4-webpack4@1.0.10 test: `karma start ./config/karma.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular7-electron4-sqlite3-bootstrap4-webpack4@1.0.10 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pamtbaau** [comment]
I can reproduce the issue in a fresh install... Unfortunately...

On the other hand, I have moved on to using Angular-cli. Only since a few releases can the cli be using in combination with custom webpack configurations. However, things have changed and I can use the goodies of angular-cli and custom webpack configurations.

I have therefor created an new starter which uses the cli. That starter has no issues with testing. Would you mind trying the other starter? 

https://github.com/pamtbaau/electron-angular-cli-sqlite-bootstrap

**Comment by mdfazuluddin** [comment]
Thanks a lot and the tests are working fine now.

The "npm run package" is failing now and I think you need to fix that also.
> electron-builder .

  • electron-builder  version=21.2.0 os=10.0.18363
  • author is missed in the package.json  appPackageFile=C:\Angular\electron-angular-cli-sqlite-bootstrap\package.json
  ⨯ Package "electron" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.
Package "electron-builder" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-cli-electron-sqlite-bootstrap@1.0.0 package: `electron-builder .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-cli-electron-sqlite-bootstrap@1.0.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pamtbaau** [comment]
Thanks for your feedback on "packaging". Totally forgot to add the "package" script and config... 

It should be working now.

**Comment by mdfazuluddin** [comment]
Thanks and now packaging is happening but the app is not running with the created .exe file which is under "electron-angular-cli-sqlite-bootstrap\dist\win-unpacked", following error it is showing
file:///C:/Angular/electron-angular-cli-sqlite-bootstrap/dist/win-unpacked/resources/app.asar/dist/index.html

Can you please fix and let me know the same.

**Comment by pamtbaau** [comment]
Did you first build the app using 'npm run build:once'? After building the packaging should work.

**Comment by mdfazuluddin** [comment]
> Did you first build the app using 'npm run build:once'? After building the packaging should work.

Yes, I did and still its not working.

**Comment by mdfazuluddin** [comment]
Sorry, its working fine now. Thanks a lot for the quick support.

I am closing this issue.
